### ISSUE TITLE
New Subtitles/Improved Subtitles

### ISSUE THREAD

**Issue by Autumnis** [JanGuillermo/LethalCompany#2]
I improved many subtitles and added many new ones, how can I contribute this to the mod?

**Comment by JanGuillermo** [comment]
@Autumnis feel free to make a PR! :)

**Comment by Autumnis** [comment]
@JanGuillermo It doesn't seem like I can make a PR, or even make a new branch at all.

**Comment by JanGuillermo** [comment]
@Autumnis Have you tried forking the project then pushing your changes there and creating a pull request from your repository into mine? ([Some helpful guide I found describing the steps](https://github.com/gabrieldemarmiesse/getting_started_open_source))

**Comment by JanGuillermo** [comment]
> The tutorial is a bit confusing, so instead I will upload a .txt file version of my modified constants.cs, which can then be resaved as a .cs and hopefully integrated into the mod. Hope it isn't too confusing. [constants.txt](https://github.com/JanGuillermo/LethalCompany/files/13573437/constants.txt)

Thank you so much, I'll address these changes and credit it to you 😊

**Comment by JanGuillermo** [comment]
Resolved with #11. The new version should be out shortly.
