### ISSUE TITLE
can i translate this into chinese and re upload it on Thunderstore?

### ISSUE THREAD

**Issue by S961** [JanGuillermo/LethalCompany#31]
I'll label the original plugin,and i already done the translate
[SubtitlesAPI.zip](https://github.com/JanGuillermo/LethalCompany/files/13630024/SubtitlesAPI.zip)

**Comment by JanGuillermo** [comment]
> I'll label the original plugin,and i already done the translate [SubtitlesAPI.zip](https://github.com/JanGuillermo/LethalCompany/files/13630024/SubtitlesAPI.zip)

@S961 Alternatively you could open a PR to add a new Chinese localization file and set the locale to CN in the config. :) I can help out if needed.

[This location](https://github.com/JanGuillermo/LethalCompany/tree/main/SubtitlesAPI/Locales) would be where you'd add a new file `ChineseSubtitleLocalization.cs` and add the configuration there.

**Comment by S961** [comment]
oops,Uploads are disabled.
[ChineseSubtitleLocalization.zip](https://github.com/JanGuillermo/LethalCompany/files/13630500/ChineseSubtitleLocalization.zip)

**Comment by S961** [comment]
i can't add the file. Uploads are disabled.

**Comment by JanGuillermo** [comment]
@S961 I added the new localization pack and it should be available on SubtitlesAPI.

Once you have the version 0.0.5, you can go to Thunderstore Mod Manager's Edit config and look for `BepInEx/config/JustJelly.SubtitlesAPI.cfg` then you can set the locale to `zh`.

**Comment by S961** [comment]
ok
