### ISSUE TITLE
Request: Subtitle mod update for LC V50

### ISSUE THREAD

**Issue by Xenomatsu** [JanGuillermo/LethalCompany#39]
Dear JanGuillermo,

Hope you're well. Any news on the mod update? As deaf person, we are highly appreciated using your mod. 

Looking forward to eagerly awaiting the mod update.

Best regards,
Xeno

**Comment by JanGuillermo** [comment]
@Xenomatsu hey, sorry about the delay, but the mod is now up to date for V64.
